project:
  type: website
  output-dir: docs

website:
  title: "barrettb.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Research
      - href: files/Resume_BarrettBuhler.pdf
        text: CV


format:
  html:
    theme: morph
    css: styles.css
    toc: true

execute:
  freeze: auto
